//! The crate root's public export list, rendered as an includable fragment.
//!
//! `kafka-wire`'s facade is flat: a caller names a message directly at the
//! crate root and never writes the module path underneath. Making the generated
//! names reachable there means naming every one of them AT the crate root, and
//! `include!` is the only construct in Rust that places items into a file from
//! another one. This module therefore emits the explicit list that `lib.rs`
//! includes without a wildcard re-export.
//!
//! Two consequences follow from the include and are visible in the output. The
//! provenance line is `//` rather than `//!`, because Rust refuses an inner doc
//! comment at an expansion site; and the file's extension is `.rsi`, because it
//! is a fragment of `lib.rs` rather than a module of its own and the guards that
//! walk `.rs` files would otherwise judge it as one.
//!
//! It deliberately decides nothing about WHICH names are public. That is
//! `module_file`'s list, consumed here, so the two cannot drift.

use crate::{group::ApiGroup, provenance::GENERATOR, source::MessageSource};

use super::{module_file::module_exports, text::RustText};

pub(crate) fn render_exports_file(
    groups: &[ApiGroup],
    unkeyed: &[MessageSource],
    commit: &str,
) -> String {
    let mut rust = RustText::default();
    rust.line(format!("// @generated by {GENERATOR}; do not edit."));
    rust.line("//");
    rust.line("// The public vocabulary of this crate, for Apache Kafka commit");
    rust.line(format!("// `{commit}`."));
    rust.line("//");
    rust.line("// Included by `lib.rs` rather than declared as a module: these names must land");
    rust.line("// at the crate root, and an inner doc comment cannot appear where an include");
    rust.line("// expands, which is why the provenance above is `//`.");
    rust.blank();

    let names = module_exports(groups, unkeyed)
        .into_iter()
        .flat_map(|(_, items)| items)
        .collect::<Vec<_>>();

    // One `pub use`, listing every name. Brace collapsing and line breaking are
    // rustfmt's, not the emitter's.
    rust.line(format!(
        "pub use crate::generated::{{{}}};",
        sorted(names).join(", ")
    ));
    rust.finish()
}

/// Alphabetical, so the diff of a new API reads as an insertion.
///
/// The per-module grouping the facade uses is the wrong order here: a reader of
/// this file is asking whether one name is public, not which module declares it.
fn sorted(mut names: Vec<String>) -> Vec<String> {
    names.sort_unstable();
    names
}
