//! Generated facade rendering for all API-pair modules.

use crate::group::ApiGroup;

use super::{api::descriptor_name, text::RustText};

pub(crate) fn render_module_file(groups: &[ApiGroup], commit: &str) -> String {
    let mut rust = RustText::default();
    rust.line("//! @generated by kafka-wire-codegen 0.1.0; do not edit.");
    rust.line("//!");
    rust.line("//! Generated module facade for Apache Kafka commit");
    rust.line(format!("//! `{commit}`."));
    rust.blank();

    let mut modules = groups
        .iter()
        .map(|group| group.module_name.as_str())
        .collect::<Vec<_>>();
    modules.push("registry");
    modules.sort_unstable();
    for module in modules {
        rust.line(format!("mod {module};"));
    }
    rust.blank();

    let mut exports = groups
        .iter()
        .map(|group| {
            let mut items = group
                .messages()
                .flat_map(|source| {
                    [
                        descriptor_name(&source.message),
                        source.message.name.rust_type().to_owned(),
                    ]
                })
                .collect::<Vec<_>>();
            items.sort_unstable();
            (group.module_name.clone(), items)
        })
        .collect::<Vec<_>>();
    exports.push((
        "registry".to_owned(),
        vec!["MESSAGE_DESCRIPTORS".to_owned()],
    ));
    exports.sort_unstable_by(|left, right| left.0.cmp(&right.0));
    for (module, items) in exports {
        render_pub_use(&mut rust, &module, &items);
    }
    rust.finish()
}

fn render_pub_use(rust: &mut RustText, module: &str, items: &[String]) {
    const WIDTH: usize = 100;

    if let [item] = items {
        rust.line(format!("pub use {module}::{item};"));
        return;
    }

    let one_line = format!("pub use {module}::{{{}}};", items.join(", "));
    if one_line.len() <= WIDTH {
        rust.line(one_line);
        return;
    }

    rust.line(format!("pub use {module}::{{"));
    render_wrapped_items(rust, items, WIDTH);
    rust.line("};");
}

fn render_wrapped_items(rust: &mut RustText, items: &[String], width: usize) {
    const INDENT: &str = "    ";

    let mut line = INDENT.to_owned();
    for item in items {
        let separator = if line == INDENT { "" } else { ", " };
        if line.len() + separator.len() + item.len() + 1 > width {
            rust.line(format!("{line},"));
            line.clear();
            line.push_str(INDENT);
            line.push_str(item);
        } else {
            line.push_str(separator);
            line.push_str(item);
        }
    }
    rust.line(format!("{line},"));
}
