//! Static protocol registry rendering.

use crate::group::ApiGroup;

use super::{api::descriptor_name, text::RustText};

pub(crate) fn render_registry(groups: &[ApiGroup], commit: &str) -> String {
    let mut rust = RustText::default();
    rust.line("//! @generated by kafka-wire-codegen 0.1.0; do not edit.");
    rust.line("//!");
    rust.line("//! Static message registry for Apache Kafka commit");
    rust.line(format!("//! `{commit}`."));
    rust.blank();
    rust.line("use crate::MessageDescriptor;");
    rust.blank();

    let constants = groups
        .iter()
        .flat_map(ApiGroup::messages)
        .map(|source| descriptor_name(&source.message))
        .collect::<Vec<_>>();
    let mut imports = constants.clone();
    imports.sort_unstable();
    rust.line("use super::{");
    render_wrapped_items(&mut rust, &imports);
    rust.line("};");
    rust.blank();

    rust.line(
        "/// All messages emitted by this pinned protocol slice, sorted by API key and direction.",
    );
    rust.line("pub const MESSAGE_DESCRIPTORS: &[MessageDescriptor] = &[");
    for constant in constants {
        rust.line(format!("    {constant},"));
    }
    rust.line("];");
    rust.finish()
}

fn render_wrapped_items(rust: &mut RustText, items: &[String]) {
    const WIDTH: usize = 100;
    const INDENT: &str = "    ";

    let mut line = INDENT.to_owned();
    for item in items {
        let separator = if line == INDENT { "" } else { ", " };
        if line.len() + separator.len() + item.len() + 1 > WIDTH {
            rust.line(format!("{line},"));
            line.clear();
            line.push_str(INDENT);
            line.push_str(item);
        } else {
            line.push_str(separator);
            line.push_str(item);
        }
    }
    rust.line(format!("{line},"));
}
