//! The whole-corpus probe accounts for every pinned schema, once.
//!
//! Scenario: run the render probe over the repository's real pinned corpus and
//! assert the shape of its answer. This is the instrument behind
//! `cargo xtask generate-all --check-only`, and an instrument that quietly
//! skipped files would report progress that is not there.
//!
//! Nothing here asserts *how many* schemas render. That number is expected to
//! move every time the backend grows, and pinning it would turn every step
//! forward into a failing test. What is pinned is that the number is honest:
//! every pinned file is classified, no file is classified twice, and every file
//! reported as rendered has Rust behind it.

use std::path::{Path, PathBuf};

use kafka_wire_codegen::{CorpusOutcome, CorpusRender, render_corpus};

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .map_or_else(|| PathBuf::from("."), Path::to_path_buf)
}

fn probe() -> CorpusRender {
    render_corpus(repository_root())
        .unwrap_or_else(|error| panic!("the corpus probe failed outright: {error}"))
}

fn pinned_files() -> usize {
    let lock = std::fs::read_to_string(repository_root().join("spec/protocol.lock"))
        .unwrap_or_else(|error| panic!("read the repository lockfile: {error}"));
    lock.matches("[[kafka.files]]").count()
}

#[test]
fn every_pinned_schema_is_classified_exactly_once() {
    let probe = probe();
    let pinned = pinned_files();

    assert!(pinned > 100, "the pinned corpus shrank to {pinned} files");
    assert_eq!(
        probe.outcomes.len(),
        pinned,
        "the probe classified {} of {pinned} pinned schemas; a schema it never \
         reaches is invisible in both the rendered count and the work queue",
        probe.outcomes.len()
    );
}

#[test]
fn the_rendered_count_and_the_work_queue_partition_the_corpus() {
    let probe = probe();
    let queued = probe
        .failure_taxonomy()
        .values()
        .map(Vec::len)
        .sum::<usize>();

    assert_eq!(
        probe.rendered() + queued,
        probe.outcomes.len(),
        "the rendered count and the failure taxonomy do not add up to the corpus"
    );
    assert!(
        probe.rendered() > 0,
        "nothing rendered at all, so every other claim here is about an empty set"
    );
}

#[test]
fn everything_reported_as_rendered_has_generated_rust_behind_it() {
    let probe = probe();

    for (filename, outcome) in &probe.outcomes {
        let CorpusOutcome::Rendered { module } = outcome else {
            continue;
        };
        let source = probe.files.get(module).unwrap_or_else(|| {
            panic!("{filename} was reported as rendered into {module}, which was never emitted")
        });
        assert!(
            source.starts_with("//! @generated by kafka-wire-codegen "),
            "{module} does not open with the generator's banner"
        );
    }

    // The facade and the registry are emitted for whatever survived, so they
    // belong to no single schema and would otherwise go unchecked.
    for facade in ["mod.rs", "registry.rs"] {
        assert!(
            probe.files.contains_key(facade),
            "the probe emitted no {facade}, so the modules it rendered are unreachable"
        );
    }
}

#[test]
fn a_refusal_is_recorded_against_a_construct_rather_than_a_message_name() {
    // The taxonomy is a work queue. Keyed on the full diagnostic it would be as
    // long as the corpus, and the one missing construct behind a hundred
    // refusals would read as a hundred separate tasks.
    let probe = probe();
    let taxonomy = probe.failure_taxonomy();

    assert!(
        taxonomy.len() < probe.outcomes.len() - probe.rendered(),
        "every refusal is its own category, so the taxonomy groups nothing"
    );
    for (cause, files) in &taxonomy {
        assert!(
            !files.is_empty(),
            "the taxonomy carries a cause with no files: {cause}"
        );
        assert!(
            !cause.contains("cannot render"),
            "a cause still carries its message and field, so it cannot group: {cause}"
        );
    }
}

#[test]
fn probing_the_same_corpus_twice_produces_the_same_answer() {
    let first = probe();
    let second = probe();

    assert_eq!(
        first.files, second.files,
        "the probe rendered different bytes for the same pinned corpus"
    );
    assert_eq!(
        first.outcomes, second.outcomes,
        "the probe classified the same pinned corpus two different ways"
    );
}
