//! Exactly one module decides which compiler produced a generated tree.
//!
//! Scenario: generate from a synthetic pinned workspace and read the stamp back
//! out of both places it appears — the banner opening every generated file and
//! the `generator` field of the manifest — then confirm no second module in the
//! generator could have supplied it.
//!
//! Two owners of that answer is one too many: a version bump moves one of them,
//! the manifest and the banner disagree from then on, and nothing fails.

mod support;

use std::{fs, path::Path};

use kafka_wire_codegen::GenerationMode;
use support::{SUPPORTED, Workspace, read, repository_root, write};

#[test]
fn a_generated_file_carries_the_provenance_of_exactly_one_generator() {
    let workspace = Workspace::pinning("provenance", &SUPPORTED);
    workspace
        .generate(GenerationMode::Write)
        .unwrap_or_else(|error| panic!("generation failed: {error}"));

    let expected = concat!("kafka-wire-codegen ", env!("CARGO_PKG_VERSION"));
    let tree = workspace.tree();
    let rust = tree
        .iter()
        .filter(|(name, _)| Path::new(name).extension().is_some_and(|kind| kind == "rs"));
    for (name, source) in rust {
        assert!(
            source.starts_with(&format!("//! @generated by {expected}; do not edit.")),
            "{name} does not open with the generator's banner"
        );
    }

    let manifest = tree
        .get("MANIFEST.json")
        .unwrap_or_else(|| panic!("generation produced no manifest"));
    assert!(
        manifest.contains(&format!("\"generator\": \"{expected}\"")),
        "the manifest names a different generator than the banner: {manifest}"
    );

    let value: serde_json::Value = serde_json::from_str(manifest)
        .unwrap_or_else(|error| panic!("decode generated manifest: {error}"));
    for field in [
        "semantic_inputs_sha256",
        "protocol_lock_sha256",
        "headers_override_sha256",
        "schema_exceptions_sha256",
        "compiler_source_sha256",
        "rustfmt_sha256",
    ] {
        let digest = value[field]
            .as_str()
            .unwrap_or_else(|| panic!("manifest has no string field {field}: {manifest}"));
        assert_eq!(digest.len(), 64, "{field} is not a SHA-256 digest");
        assert!(
            digest.bytes().all(|byte| byte.is_ascii_hexdigit()),
            "{field} is not hexadecimal: {digest}"
        );
    }
    assert!(
        value["rustfmt_identity"]
            .as_str()
            .is_some_and(|identity| identity.contains("rustfmt") && identity.contains("2024")),
        "manifest does not identify formatter behavior: {manifest}"
    );
}

#[test]
fn changing_an_override_document_changes_semantic_provenance() {
    let workspace = Workspace::pinning("provenance-override", &SUPPORTED);
    workspace
        .generate(GenerationMode::Write)
        .unwrap_or_else(|error| panic!("generation failed: {error}"));
    let first: serde_json::Value = serde_json::from_str(
        workspace
            .tree()
            .get("MANIFEST.json")
            .unwrap_or_else(|| panic!("generation produced no manifest")),
    )
    .unwrap_or_else(|error| panic!("decode first manifest: {error}"));

    let headers = workspace.root.join("spec/overrides/headers.toml");
    write(&headers, "schema = 1\n# reviewed empty exception set\n");
    workspace
        .generate(GenerationMode::Write)
        .unwrap_or_else(|error| panic!("regeneration failed: {error}"));
    let second: serde_json::Value = serde_json::from_str(
        workspace
            .tree()
            .get("MANIFEST.json")
            .unwrap_or_else(|| panic!("regeneration produced no manifest")),
    )
    .unwrap_or_else(|error| panic!("decode second manifest: {error}"));

    assert_ne!(
        first["headers_override_sha256"], second["headers_override_sha256"],
        "changed override bytes kept the same component digest"
    );
    assert_ne!(
        first["semantic_inputs_sha256"], second["semantic_inputs_sha256"],
        "changed override bytes kept the same aggregate provenance"
    );
    assert_eq!(
        first["protocol_lock_sha256"], second["protocol_lock_sha256"],
        "an unchanged lockfile digest moved"
    );
}

#[test]
fn provenance_is_the_only_module_that_names_the_generator() {
    // Two places that decide "which compiler produced this" is one place too
    // many: a release bumps one and the manifest disagrees with the banner
    // forever after, with nothing failing.
    let source_root = repository_root().join("crates/kafka-wire-codegen/src");
    let mut owners = Vec::new();
    let mut pending = vec![source_root.clone()];

    while let Some(directory) = pending.pop() {
        let entries = fs::read_dir(&directory)
            .unwrap_or_else(|error| panic!("read {}: {error}", directory.display()));
        for entry in entries {
            let path = entry
                .unwrap_or_else(|error| panic!("read entry: {error}"))
                .path();
            if path.is_dir() {
                pending.push(path);
                continue;
            }
            if path.extension().is_none_or(|extension| extension != "rs") {
                continue;
            }
            if read(&path).contains("CARGO_PKG_VERSION") {
                owners.push(
                    path.strip_prefix(&source_root)
                        .unwrap_or(&path)
                        .to_string_lossy()
                        .into_owned(),
                );
            }
        }
    }

    owners.sort();
    assert_eq!(
        owners,
        vec!["provenance.rs".to_owned()],
        "generator identity must be decided in provenance.rs and nowhere else"
    );
}
