//! Exactly one module decides which compiler produced a generated tree.
//!
//! Scenario: generate from a synthetic pinned workspace and read the stamp back
//! out of both places it appears — the banner opening every generated file and
//! the `generator` field of the manifest — then confirm no second module in the
//! generator could have supplied it.
//!
//! Two owners of that answer is one too many: a version bump moves one of them,
//! the manifest and the banner disagree from then on, and nothing fails.

mod support;

use std::{fs, path::Path};

use kafka_wire_codegen::GenerationMode;
use support::{SUPPORTED, Workspace, read, repository_root};

#[test]
fn a_generated_file_carries_the_provenance_of_exactly_one_generator() {
    let workspace = Workspace::pinning("provenance", &SUPPORTED);
    workspace
        .generate(GenerationMode::Write)
        .unwrap_or_else(|error| panic!("generation failed: {error}"));

    let expected = concat!("kafka-wire-codegen ", env!("CARGO_PKG_VERSION"));
    let tree = workspace.tree();
    let rust = tree
        .iter()
        .filter(|(name, _)| Path::new(name).extension().is_some_and(|kind| kind == "rs"));
    for (name, source) in rust {
        assert!(
            source.starts_with(&format!("//! @generated by {expected}; do not edit.")),
            "{name} does not open with the generator's banner"
        );
    }

    let manifest = tree
        .get("MANIFEST.json")
        .unwrap_or_else(|| panic!("generation produced no manifest"));
    assert!(
        manifest.contains(&format!("\"generator\": \"{expected}\"")),
        "the manifest names a different generator than the banner: {manifest}"
    );
}

#[test]
fn provenance_is_the_only_module_that_names_the_generator() {
    // Two places that decide "which compiler produced this" is one place too
    // many: a release bumps one and the manifest disagrees with the banner
    // forever after, with nothing failing.
    let source_root = repository_root().join("crates/kafka-wire-codegen/src");
    let mut owners = Vec::new();
    let mut pending = vec![source_root.clone()];

    while let Some(directory) = pending.pop() {
        let entries = fs::read_dir(&directory)
            .unwrap_or_else(|error| panic!("read {}: {error}", directory.display()));
        for entry in entries {
            let path = entry
                .unwrap_or_else(|error| panic!("read entry: {error}"))
                .path();
            if path.is_dir() {
                pending.push(path);
                continue;
            }
            if path.extension().is_none_or(|extension| extension != "rs") {
                continue;
            }
            if read(&path).contains("CARGO_PKG_VERSION") {
                owners.push(
                    path.strip_prefix(&source_root)
                        .unwrap_or(&path)
                        .to_string_lossy()
                        .into_owned(),
                );
            }
        }
    }

    owners.sort();
    assert_eq!(
        owners,
        vec!["provenance.rs".to_owned()],
        "generator identity must be decided in provenance.rs and nowhere else"
    );
}
