//! Layout belongs to `rustfmt`, and a formatter that cannot run stops generation.
//!
//! Scenario: hand the formatter deliberately mis-laid-out Rust and assert the
//! text that comes back is `rustfmt`'s and not the emitter's, then take the
//! formatter away and assert generation fails loudly with nothing half-done.
//!
//! This re-proves a milestone claim that previously rested on manual probes
//! that were reverted. The claim matters because the emitter writes one item
//! per line with fixed indentation: if that reached disk directly, generated
//! files would drift out of agreement with `cargo fmt --all --check` the first
//! time anyone changed `rustfmt.toml`.

use std::{
    collections::BTreeMap,
    path::{Path, PathBuf},
};

use crate::{GenerationError, format::format_rendered_rust};

/// The repository checkout, whose `rustfmt.toml` the formatter must honor.
///
/// Running the formatter anywhere else would prove layout came from *some*
/// rustfmt, not from the one the generated tree is checked against.
fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .map_or_else(|| PathBuf::from("."), Path::to_path_buf)
}

/// A directory that does not exist, so the formatter cannot be launched at all.
fn missing_workspace() -> PathBuf {
    workspace_root().join("no-such-directory-for-the-formatter-probe")
}

fn rendered(files: &[(&str, &str)]) -> BTreeMap<String, String> {
    files
        .iter()
        .map(|(path, source)| ((*path).to_owned(), (*source).to_owned()))
        .collect()
}

#[test]
fn generated_layout_is_rustfmt_s_and_not_the_emitter_s() {
    // Everything wrong here is a layout decision: collapsed braces, no spacing
    // around the type colon, a run of blank lines, and a `use` group written on
    // one line. An emitter that owned layout would preserve all of it.
    let emitted = "//! @generated by a test.\n\
                   \n\
                   \n\
                   \n\
                   use std::{collections::BTreeMap,fmt::Debug};\n\
                   \n\
                   pub   struct  Probe{pub topic_name:String,pub partition_index:i32}\n\
                   \n\
                   impl Probe{pub fn is_empty(&self)->bool{self.topic_name.is_empty()}}\n";

    let formatted = format_rendered_rust(rendered(&[("probe.rs", emitted)]), &workspace_root())
        .unwrap_or_else(|error| panic!("the formatter rejected valid Rust: {error}"));
    let probe = formatted
        .get("probe.rs")
        .unwrap_or_else(|| panic!("the formatter dropped the file it was given"));

    assert_eq!(
        probe,
        "//! @generated by a test.\n\
         \n\
         use std::{collections::BTreeMap, fmt::Debug};\n\
         \n\
         pub struct Probe {\n\
         \x20   pub topic_name: String,\n\
         \x20   pub partition_index: i32,\n\
         }\n\
         \n\
         impl Probe {\n\
         \x20   pub fn is_empty(&self) -> bool {\n\
         \x20       self.topic_name.is_empty()\n\
         \x20   }\n\
         }\n"
    );
}

#[test]
fn formatting_already_formatted_rust_is_a_fixed_point() {
    // Determinism at the layout layer: the manifest hashes formatted bytes, so
    // a formatter that kept nudging its own output would make every generation
    // report a change.
    let source = "//! @generated by a test.\n\npub struct Probe {\n    pub index: i32,\n}\n";

    let once = format_rendered_rust(rendered(&[("probe.rs", source)]), &workspace_root())
        .unwrap_or_else(|error| panic!("first format failed: {error}"));
    let twice = format_rendered_rust(once.clone(), &workspace_root())
        .unwrap_or_else(|error| panic!("second format failed: {error}"));

    assert_eq!(once, twice, "formatting is not idempotent");
    assert_eq!(
        once.get("probe.rs").map(String::as_str),
        Some(source),
        "already-formatted Rust was rewritten"
    );
}

#[test]
fn a_file_the_formatter_rejects_fails_generation_and_names_it() {
    let broken = "//! @generated by a test.\n\npub fn probe( {\n";

    let error = format_rendered_rust(rendered(&[("probe.rs", broken)]), &workspace_root())
        .err()
        .unwrap_or_else(|| panic!("the formatter accepted Rust it cannot parse"));

    assert!(
        matches!(error, GenerationError::Formatter { .. }),
        "a rejected file must be reported as a formatter failure: {error:?}"
    );
    let reported = error.to_string();
    assert!(
        reported.contains("probe.rs"),
        "the failure must name the generated file: {reported}"
    );
    assert!(
        reported.contains("unclosed delimiter"),
        "the failure must carry rustfmt's own diagnostic: {reported}"
    );
}

#[test]
fn one_rejected_file_discards_the_whole_batch() {
    // The caller writes what this function returns. Returning the files that
    // happened to format before the failure is how a partial tree reaches disk.
    let batch = rendered(&[
        ("first.rs", "//! @generated by a test.\n\npub struct A;\n"),
        ("second.rs", "//! @generated by a test.\n\npub fn b( {\n"),
        ("third.rs", "//! @generated by a test.\n\npub struct C;\n"),
    ]);

    let result = format_rendered_rust(batch, &workspace_root());

    assert!(
        result.is_err(),
        "a batch containing one unparseable file returned formatted output"
    );
}

#[test]
fn a_formatter_that_cannot_be_launched_fails_loudly_with_a_repair_instruction() {
    // rustfmt is spawned with the workspace root as its working directory, so a
    // root that does not exist reproduces exactly what a missing or unusable
    // formatter does: the process never starts.
    let error = format_rendered_rust(
        rendered(&[(
            "probe.rs",
            "//! @generated by a test.\n\npub struct Probe;\n",
        )]),
        &missing_workspace(),
    )
    .err()
    .unwrap_or_else(|| panic!("generation succeeded without running a formatter"));

    assert!(
        matches!(error, GenerationError::FormatterUnavailable { .. }),
        "an unlaunchable formatter must be its own error: {error:?}"
    );
    let reported = error.to_string();
    assert!(
        reported.contains("rustfmt owns generated layout"),
        "the failure must say why generation stopped: {reported}"
    );
    assert!(
        reported.contains("rustup component add rustfmt") && reported.contains("RUSTFMT"),
        "the failure must tell the operator how to repair it: {reported}"
    );
}
