//! Compiler identity stamped into every generated artifact.
//!
//! This module owns the single answer to "which generator produced this tree",
//! and the `@generated` banner that carries it into Rust source. The version is
//! read from the generator's own package metadata so a release cannot leave a
//! stale number behind in the manifest or the banner.
//!
//! It deliberately does not own upstream protocol provenance — repository,
//! commit, and source digests come from the lockfile.

/// Name and version of the compiler that produced the generated tree.
pub(crate) const GENERATOR: &str = concat!("kafka-wire-codegen ", env!("CARGO_PKG_VERSION"));

/// Returns the provenance banner that opens every generated Rust file.
pub(crate) fn generated_banner() -> String {
    format!("//! @generated by {GENERATOR}; do not edit.")
}
