[package]
name = "kafka-wire"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Generated, version-aware Kafka wire messages"
publish = ["crates-io"]
readme = "README.md"
keywords = ["kafka", "wire-format", "serialization"]
categories = ["encoding", "network-programming"]

[dependencies]
bytes.workspace = true
kafka-wire-core = { version = "0.1.0", path = "../kafka-wire-core" }

[dev-dependencies]
bytes.workspace = true

[lints]
workspace = true
