//! On-disk shape of authored vector plans and generated byte vectors.
//!
//! This module owns the two file formats under `spec/`: the hand-authored plan
//! that says which protocol situations are worth covering, and the generated
//! vector file that records what Kafka's own writer produced for each of them.
//! It owns reading and writing both, and the ordering that makes a refresh
//! reproduce byte-identical files.
//!
//! It deliberately owns no authority over the bytes themselves. Every `hex`
//! value here arrives from the Java oracle; nothing in this module may compute
//! or adjust one, because a vector this repository derived from its own encoder
//! would prove nothing.

use std::{collections::BTreeMap, fs, path::Path};

use serde::{Deserialize, Serialize};

/// Direction of one Kafka message, as declared by its upstream schema.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "lowercase")]
pub(crate) enum Direction {
    Request,
    Response,
}

/// One message's authored coverage plan.
///
/// `api_key`, `valid_versions`, and `flexible_versions` are transcribed by hand
/// from the vendored upstream JSONC rather than derived from this repository's
/// lowering. That independence is the point: a conformance run compares them
/// against the generated descriptors, so a mistake in lowering `flexibleVersions`
/// fails instead of agreeing with itself.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub(crate) struct Plan {
    pub(crate) schema: u32,
    pub(crate) message: String,
    pub(crate) api_key: i16,
    pub(crate) direction: Direction,
    pub(crate) valid_versions: Vec<i16>,
    pub(crate) flexible_versions: Vec<i16>,
    pub(crate) source: String,
    pub(crate) cases: Vec<PlanCase>,
}

/// One protocol situation, and the versions at which it is meaningful.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub(crate) struct PlanCase {
    pub(crate) name: String,
    /// Why this case earns its place in the corpus.
    pub(crate) why: String,
    pub(crate) versions: Vec<i16>,
    pub(crate) json_value: serde_json::Value,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub(crate) unknown_tagged_fields: Vec<TaggedFieldPlan>,
}

/// One unknown tagged field, which no generated JSON converter can express.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub(crate) struct TaggedFieldPlan {
    pub(crate) tag: u32,
    pub(crate) data_hex: String,
}

/// Every vector for one message at one version.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub(crate) struct VectorFile {
    pub(crate) schema: u32,
    pub(crate) vectors: Vec<Vector>,
}

/// One broker-authored byte vector.
///
/// Each vector repeats its message identity so that a vector quoted on its own —
/// in a bug report, or in a failing assertion — is still complete.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub(crate) struct Vector {
    pub(crate) name: String,
    pub(crate) why: String,
    pub(crate) message: String,
    pub(crate) api_key: i16,
    pub(crate) direction: Direction,
    pub(crate) version: i16,
    pub(crate) flexible: bool,
    pub(crate) json_value: serde_json::Value,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub(crate) unknown_tagged_fields: Vec<TaggedFieldPlan>,
    /// Lowercase hex of the message body, authored by Apache Kafka's own writer.
    pub(crate) hex: String,
}

/// Format revision written by this xtask and required by the conformance crate.
pub(crate) const SCHEMA: u32 = 1;

pub(crate) fn plan_root(workspace: &Path) -> std::path::PathBuf {
    workspace.join("spec").join("vector-plans")
}

pub(crate) fn vector_root(workspace: &Path) -> std::path::PathBuf {
    workspace.join("spec").join("vectors")
}

/// Read every authored plan, sorted by message so a refresh is order-stable.
pub(crate) fn load_plans(workspace: &Path) -> Result<Vec<Plan>, String> {
    let root = plan_root(workspace);
    let entries = fs::read_dir(&root)
        .map_err(|error| format!("read vector plans in {}: {error}", root.display()))?;

    let mut plans = BTreeMap::new();
    for entry in entries {
        let path = entry
            .map_err(|error| format!("read entry in {}: {error}", root.display()))?
            .path();
        if path.extension().and_then(|extension| extension.to_str()) != Some("json") {
            continue;
        }

        let plan: Plan = read_json(&path)?;
        if plan.schema != SCHEMA {
            return Err(format!(
                "{}: plan schema {} is not the supported schema {SCHEMA}",
                path.display(),
                plan.schema
            ));
        }
        plans.insert(plan.message.clone(), plan);
    }

    if plans.is_empty() {
        return Err(format!(
            "no vector plans found in {}; a refresh with nothing to author \
             would leave the corpus silently empty",
            root.display()
        ));
    }
    Ok(plans.into_values().collect())
}

/// Read every checked-in vector file, keyed by its path for diagnostics.
pub(crate) fn load_vector_files(workspace: &Path) -> Result<Vec<(String, VectorFile)>, String> {
    let root = vector_root(workspace);
    let mut files = BTreeMap::new();

    let messages = fs::read_dir(&root)
        .map_err(|error| format!("read vectors in {}: {error}", root.display()))?;
    for message in messages {
        let directory = message
            .map_err(|error| format!("read entry in {}: {error}", root.display()))?
            .path();
        if !directory.is_dir() {
            continue;
        }

        let versions = fs::read_dir(&directory)
            .map_err(|error| format!("read vectors in {}: {error}", directory.display()))?;
        for version in versions {
            let path = version
                .map_err(|error| format!("read entry in {}: {error}", directory.display()))?
                .path();
            if path.extension().and_then(|extension| extension.to_str()) != Some("json") {
                continue;
            }
            let file: VectorFile = read_json(&path)?;
            files.insert(relative(workspace, &path), file);
        }
    }

    Ok(files.into_iter().collect())
}

/// Replace one version's vector file, creating its message directory as needed.
pub(crate) fn write_vector_file(
    workspace: &Path,
    message: &str,
    version: i16,
    file: &VectorFile,
) -> Result<String, String> {
    let directory = vector_root(workspace).join(message);
    fs::create_dir_all(&directory)
        .map_err(|error| format!("create {}: {error}", directory.display()))?;

    let path = directory.join(format!("v{version}.json"));
    let mut rendered = serde_json::to_string_pretty(file)
        .map_err(|error| format!("render {}: {error}", path.display()))?;
    rendered.push('\n');
    fs::write(&path, rendered).map_err(|error| format!("write {}: {error}", path.display()))?;

    Ok(relative(workspace, &path))
}

/// Remove vector files for messages or versions no plan still authors.
pub(crate) fn remove_vector_file(workspace: &Path, path: &str) -> Result<(), String> {
    let absolute = workspace.join(path);
    fs::remove_file(&absolute).map_err(|error| format!("remove {}: {error}", absolute.display()))
}

fn read_json<T: serde::de::DeserializeOwned>(path: &Path) -> Result<T, String> {
    let source =
        fs::read_to_string(path).map_err(|error| format!("read {}: {error}", path.display()))?;
    serde_json::from_str(&source).map_err(|error| format!("parse {}: {error}", path.display()))
}

fn relative(workspace: &Path, path: &Path) -> String {
    path.strip_prefix(workspace)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}
